eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka/, http://eureka-2:8762/eureka/

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.config: DEBUG



spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/hyunkook/Work/01_GitHub/study-msa/config-repo/
  application:
    name: config

#        git:
#          uri: https://github.com/Hyunk00k/study-msa
#          basedir: target/config
#          search-paths: config-repo #subdirectory
#          default-label: study/msa-2 #branch



---
#config-1
spring:
  profiles: config-1

server:
  port: 9011

---
#config-2
spring:
  profiles: config-2

server:
  port: 9012

