imports:
  - { resource: ./eureka-local.yml}
  - { resource: ./zipkin-local.yml}

server:
  port: 8101

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 1000
      routes:
        - id: gateway
          uri: lb://API-A
          predicates:
            - Path=/api-a/**
          filters:
            - RewritePath=/api-a/(?<segment>.*), /$\{segment}
        - id: gateway
          uri: lb://API-B
          predicates:
            - Path=/api-b/**
          filters:
            - RewritePath=/api-b/(?<segment>.*), /$\{segment}

      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 3
            series: # empty
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            exceptions:
              - java.net.ConnectException

logging:
  level:
    org.springframework.cloud.gateway: TRACE
