eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

server:
  port: 8092

spring:
  application:
    name: gateway

zuul:
  routes:
    app-api:
        path: /app/**
        stripPrefix: false
