management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    instance-info-replication-interval-seconds: 2
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    appname: eureka

spring:
  profiles:
    active: eureka-1

---
#eureka-1
server:
  port: 8761
spring:
  profiles: eureka-1
eureka:
  instance:
    hostname: eureka-1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone:  http://eureka-2:8762/eureka/

---
#eureka-2
server:
  port: 8762
spring:
  profiles: eureka-2
eureka:
  instance:
    hostname: eureka-2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone:  http://eureka-1:8761/eureka/